"""Explicit Phase-1 type inventory -- the allowlist.

NON-PRODUCTION SPECIFICATION MATERIAL.

[A5] Every type the Phase-1 wire contract may contain, named once.  A regex
deny-list cannot stop a Gate concept entering under an unanticipated name; an
allowlist can, because adding a type requires a deliberate edit here.

Generated once from registry.py and then FROZEN.  Regenerating it to silence a
failure defeats its purpose: the check exists to make additions visible.
"""

from __future__ import annotations

PHASE1_TYPE_INVENTORY: frozenset[str] = frozenset(
    {
        'Instant',
        'Signature',
        'HalfOpenInterval',
        'SymbolRef',
        'SymbolRefTemplate',
        'ScaledSort',
        'EnumSort',
        'Sort',
        'IntRange',
        'ScaledRange',
        'EnumDomain',
        'Domain',
        'VScaled',
        'VEnum',
        'Value',
        'QueryVar',
        'Bin',
        'MulConst',
        'Scale',
        'Rescale',
        'Ite',
        'Arm',
        'EnumTable',
        'Term',
        'QBin',
        'QMulConst',
        'QScale',
        'QRescale',
        'QIte',
        'QArm',
        'QEnumTable',
        'QTerm',
        'ActionField',
        'Action',
        'ConsequentialAction',
        'FieldSpec',
        'ActionKindSpec',
        'ActionSchema',
        'PredicateSpec',
        'PredicateSchema',
        'FieldTerm',
        'ActionTerm',
        'ProgramRule',
        'DecisionProgram',
        'ImplicationRule',
        'DefinitionRule',
        'EntailmentRule',
        'EntailmentRules',
        'AdmissibilityDescriptor',
        'AdmissibilityDescriptors',
        'DisclosureEntry',
        'DisclosurePolicy',
        'RatificationRecord',
        'RatificationSet',
        'BundleManifest',
        'SignedManifest',
        'ExactValue',
        'ClosedLowerBound',
        'ClosedUpperBound',
        'EnumSubset',
        'AcquisitionRelation',
        'AcquisitionPayload',
        'VerificationReceipt',
        'StatementRecord',
        'InterestAssessment',
        'PartyRecord',
        'CaseConstructionRecord',
        'Retraction',
        'Declaration',
        'TranscriptPrefix',
        'TranscriptEntry',
        'AttestedBy',
        'EntailedBy',
        'Justification',
        'EstablishedFact',
        'StructuralDeriv',
        'AdverseDeriv',
        'BracketDeriv',
        'StipulationDeriv',
        'AttestedRelationDeriv',
        'PolicyEntailmentDeriv',
        'ConstraintDerivation',
        'Constraint',
        'NonEffect',
        #  [G1 -- section 12.4] Source authority.  Added deliberately, which is
        #  what this allowlist is for: three types the ratified contract names
        #  (ResourceScope, AuthorityGrant, AuthorityRegistrySnapshot), the
        #  generated signing body, its signed wrapper, and the revocation
        #  family that moved out of the auxiliary domain table for the same
        #  reason -- Q-12(f) has to resolve a revocation snapshot, and an
        #  untenanted, unsigned digest list cannot carry a tenant or a
        #  publisher.
        'ResourceScope',
        'AuthorityGrant',
        'AuthorityRegistrySnapshot',
        'AuthorityRegistrySnapshotBody',
        'SignedAuthorityRegistrySnapshot',
        'RevocationSnapshot',
        'RevocationSnapshotBody',
        'SignedRevocationSnapshot',
        #  [E] The fleet catalog.  Separate from the authority family above and
        #  not merely filed apart: no authority type references any of these,
        #  and Q-12 takes no catalog argument, so a profile cannot reach an
        #  admission decision.
        'AgentProfile',
        'AgentCatalogSnapshot',
        'AgentCatalogSnapshotBody',
        'SignedAgentCatalogSnapshot',
        'AuthorizationContext',
        'RebuildInputs',
        'CaseRevision',
        'RevisionLineage',
        'Binding',
        'World',
        'QueryDecl',
        'LabeledAssertion',
        'EnumDeclaration',
        'SolverQuery',
        'SolverFingerprint',
        'TruncatedReachable',
        'ReachableActions',
        'DeletionWitness',
        'ProvenSupport',
        'UnprovenSupport',
        'SupportResult',
        'InvariantOutcome',
        'DivergentOutcome',
        'InfeasibleOutcome',
        'IndeterminateOutcome',
        'AnalysisOutcome',
        'LogicalCase',
        'KernelAnalysisRecord',
        'EvidenceTarget',
        'EvidenceRequest',
        'HumanEscalation',
        'PlanningOutcome',
        'PlanningRecord',
        'DiagnosticAnnex',
        'AnalysisCertificate',
        'InternalAnalysisRecord',
        'CommitmentLeaf',
        'CommitmentRoot',
        'ProofStep',
        'CommitmentEnvelope',
        'SignedCommitmentEnvelope',
        'Disclosure',
        'ParticipantView',
        'AuditorView',
        'RatificationRecordBody',
        'StatementRecordBody',
        'InterestAssessmentBody',
        'CaseConstructionRecordBody',
        'RetractionBody',
        'DeclarationBody',
        'RevisionLineageBody',
    }
)
